# core/urls.py

from django.urls import path
from .views import (
    UserDetailView,
    DepositProductListView,
    DepositProductDetailView,
    UpdateJoinedProductsView,
    DeleteDepositProductView,
    JoinedProductsUpdateView, 
    SavingsProductListView,
    SavingsProductDetailView,
    FetchDepositProductsView,
    FetchSavingsProductsView,
    ExchangeRateAPIView,
    # SearchBanksView,
    ProfileView, update_profile_img, IncomeCalculatorView,
    CustomRegisterView,
    HighDividendStocksView,
    fetch_recent_ii_business,
    GPTSummaryView,
    fetch_and_summarize_business,
    BusinessReportDetailView,
    # recommend_products,
    join_product, get_joined_products,
    deposit_recommend,
    saving_recommend,
    deposit_recommend_second,
    saving_recommend_second,
    IncomeRatioView,
    remove_product,
    top_joined_products
)

urlpatterns = [
    path('rest-auth/registration/', CustomRegisterView.as_view(), name='custom_rest_register'),
    path('user/<int:user_id>/', UserDetailView.as_view(), name='user-detail'),
    path('update-joined-products/', UpdateJoinedProductsView.as_view(), name='update-joined-products'),
    path('delete-deposit-product/<int:product_id>/', DeleteDepositProductView.as_view(), name='delete-deposit-product'),
    path('joined-products/update/', JoinedProductsUpdateView.as_view(), name='update-joined-products'),
    path('fetch-deposit-products/', FetchDepositProductsView.as_view(), name='fetch-deposit-products'),
    path('fetch-savings-products/', FetchSavingsProductsView.as_view(), name='fetch-savings-products'),
    path('deposit-products/', DepositProductListView.as_view(), name='deposit-product-list'),
    path('savings-products/', SavingsProductListView.as_view(), name='savings-product-list'),
    path('deposits/', DepositProductListView.as_view(), name='deposit-list'),
    path('deposits/<int:pk>/', DepositProductDetailView.as_view(), name='deposit-detail'),
    path('savings/', SavingsProductListView.as_view(), name='savings-list'),
    path('savings/<int:pk>/', SavingsProductDetailView.as_view(), name='savings-detail'),
    path("exchange-rates/", ExchangeRateAPIView.as_view(), name="exchange-rates"),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("update_profile_img/", update_profile_img, name="update-profile-img"),
    path('income-calculator/', IncomeCalculatorView.as_view(), name='income-calculator'),    
    path('high-dividend-stocks/', HighDividendStocksView.as_view(), name='high-dividend-stocks'),
    path("fetch-recent-ii-business/", fetch_recent_ii_business, name="fetch-recent-ii-business"),
    path('gpt-summary/<int:report_id>/', GPTSummaryView.as_view(), name='gpt-summary'),
    path('fetch-and-summarize-business/', fetch_and_summarize_business, name='fetch-and-summarize-business'),
    path('business-report/<int:report_id>/', BusinessReportDetailView.as_view(), name='business-report-detail'),
    # path('recommend-products/', recommend_products, name='recommend-products'),
    path("join-product/", join_product, name="join-product"),
    path("joined-products/", get_joined_products, name="joined-products"),
    path("remove-product/", remove_product, name="remove-product"),
    path('recommend/deposit/<str:username>/', deposit_recommend, name='deposit-recommend'),
    path('recommend/saving/<str:username>/', saving_recommend, name='saving-recommend'),
    path('recommend/deposit/age/<str:username>/', deposit_recommend_second, name='deposit-recommend-age'),
    path('recommend/saving/age/<str:username>/', saving_recommend_second, name='saving-recommend-age'),
    path("income-ratio/", IncomeRatioView.as_view(), name="income-ratio"),
    path('top-joined-products/', top_joined_products, name='top-joined-products'),
    ]
